; Auto-generated. Do not edit!


(cl:in-package ros_action-msg)


;//! \htmlinclude ros_actionResult.msg.html

(cl:defclass <ros_actionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ros_actionResult (<ros_actionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ros_actionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ros_actionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ros_action-msg:<ros_actionResult> is deprecated: use ros_action-msg:ros_actionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <ros_actionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ros_action-msg:success-val is deprecated.  Use ros_action-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ros_actionResult>) ostream)
  "Serializes a message object of type '<ros_actionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ros_actionResult>) istream)
  "Deserializes a message object of type '<ros_actionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ros_actionResult>)))
  "Returns string type for a message object of type '<ros_actionResult>"
  "ros_action/ros_actionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ros_actionResult)))
  "Returns string type for a message object of type 'ros_actionResult"
  "ros_action/ros_actionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ros_actionResult>)))
  "Returns md5sum for a message object of type '<ros_actionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ros_actionResult)))
  "Returns md5sum for a message object of type 'ros_actionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ros_actionResult>)))
  "Returns full string definition for message of type '<ros_actionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ros_actionResult)))
  "Returns full string definition for message of type 'ros_actionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ros_actionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ros_actionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ros_actionResult
    (cl:cons ':success (success msg))
))
